"""The pruned presets of Phase 6 (terms.presets, generated by scripts/presets.py): nested, made
of trigger-query term names of both levels, no effect at a non-trigger query, and usable in
the noise and the effective loss. Their validation against the runs is in the report."""
from __future__ import annotations

import math

import pytest
import torch

from icl import EffectiveLoss, generate_icl_batch, measure_variables
from icl.theory.terms import PRESETS, nontrigger_terms_mu, trigger_terms, trigger_terms_ell
from icl.theory.terms import nontrigger
from icl.theory.terms.presets import ADDED, DROPPED
from icl.theory.terms.table import NONTRIGGER_LABELS

V, L, K, BETA = 48, 96, 9, 0.25
OP = {"M_on": 6.0, "M_off": 0.03, "Q_on": 9.0, "Q_T": -0.7, "G_on": 5.0, "G_T": -0.8,
      "var_M_on": 0.4, "var_M_off": 0.05, "var_Q_on": 1.3, "var_Q_T": 0.6, "var_Q_N": 0.2,
      "var_G_on": 0.5, "var_G_T": 0.3, "var_G_N": 0.2}
ORDER = ("counting", "pruned", "pruned_late", "compact", "minimal")


def test_presets_are_nested_and_registered():
    assert tuple(ADDED) == ORDER == tuple(DROPPED)
    for smaller, larger in zip(ORDER, ORDER[1:]):
        assert DROPPED[smaller] < DROPPED[larger], (smaller, larger)
    assert set(PRESETS) >= set(ORDER)
    assert NONTRIGGER_LABELS == (nontrigger.S_LABEL, nontrigger.MU_LABEL)


def test_presets_name_terms_of_both_levels():
    """Every dropped name is a term given ell; those without a spread are terms given S too."""
    ell = trigger_terms_ell(torch.tensor([40]), torch.tensor([2]), OP, BETA, L, V, K)
    variables = measure_variables(generate_icl_batch(64, V, L, K, generator=torch.Generator().manual_seed(0)), [L])
    given_S = trigger_terms(variables, OP, BETA, L)
    names_ell, names_S = {t.name for t in ell}, {t.name for t in given_S}
    for preset in ORDER:
        assert DROPPED[preset] <= names_ell, preset
        assert {n for n in DROPPED[preset] if "/spread/" not in n} <= names_S, preset
        kept = ell.resolve(preset)
        assert kept == names_ell - DROPPED[preset]
        assert given_S.resolve(preset) == names_S - DROPPED[preset]


def test_minimal_keeps_the_signal_and_the_target_spread():
    for name in ("on/mean/signal", "on,on/spread/signal*signal", "on,on/attention/C_phi.incoherent",
                 "T,T/attention/C_all.token_coherent.BB"):
        assert name not in DROPPED["minimal"], name


def test_presets_keep_every_term_at_a_nontrigger_query():
    table = nontrigger_terms_mu(torch.tensor([30, 90]), OP, BETA, L, V, K)
    for preset in ORDER:
        assert table.resolve(preset) == {t.name for t in table}, preset


@pytest.mark.parametrize("method", ["mean", "mc"])
def test_presets_in_the_effective_loss(method):
    """Each preset gives a finite loss within 10% of the full one."""
    full = EffectiveLoss(V, L, K, BETA, method=method, num_samples=16)(OP).item()
    for preset in ORDER:
        value = EffectiveLoss(V, L, K, BETA, method=method, num_samples=16, keep=preset)(OP).item()
        assert math.isfinite(value) and abs(value - full) < 0.1 * abs(full), (preset, value, full)
